In [1]:
#import sys
#!{sys.executable} -m pip install --user numpy
#!{sys.executable} -m pip install --user scikit-learn

In [2]:
#from google.colab import drive
#drive.mount('/content/drive')

In [3]:
import numpy as np
from numpy import genfromtxt


import warnings
warnings.filterwarnings('ignore')

In [4]:
data = genfromtxt("datasets/bank_note_data.txt", delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:, 4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:, 0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [7]:
X = features
y = labels

# Splitting the Data

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [10]:
X_train

array([[-1.2943  ,  2.6735  , -0.84085 , -2.0323  ],
       [-0.40857 ,  3.0977  , -2.9607  , -2.6892  ],
       [-1.5228  , -6.4789  ,  5.7568  ,  0.87325 ],
       ...,
       [ 0.6005  ,  0.99945 , -2.2126  ,  0.097399],
       [ 2.0165  , -0.25246 ,  5.1707  ,  1.0763  ],
       [-2.0759  , 10.8223  ,  2.6439  , -4.837   ]])

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler_obj = MinMaxScaler()

In [13]:
scaler_obj.fit(X_train)

MinMaxScaler()

In [14]:
scaled_X_train = scaler_obj.transform(X_train)

In [15]:
scaled_X_test = scaler_obj.transform(X_test)

In [16]:
scaled_X_test

array([[0.38009937, 0.11250267, 0.66790876, 0.66254348],
       [0.87793234, 0.51420791, 0.24176708, 0.86962129],
       [0.36253236, 0.6533469 , 0.14420919, 0.38041779],
       ...,
       [0.3516936 , 0.62841491, 0.12375988, 0.52382069],
       [0.54302476, 0.64885668, 0.03868008, 0.3882538 ],
       [0.19293425, 0.74247045, 0.25236091, 0.22653105]])

# Build the Neutral Network

In [17]:
#!pip install keras

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [19]:
#pip install --upgrade tensorflow

In [20]:
#creating the model in a sequence
model = Sequential()

#first layer of neural network, it has 4 neurons
#input_dim = input dimension - number of columns in input dataset
model.add(Dense(4, input_dim=4, activation='relu'))

#second hidden layer of neural network with 2 neurons
model.add(Dense(2, activation='relu'))

# Output layer of neural network with 1 neuron
# with sigmoid we only get 0 or 1
# whenever output is binary, sigmoid is used
model.add(Dense(1, activation='sigmoid'))

# Compile Model

In [21]:
# compile model
# optimizer: kinda helps with gradient descent
# optimizer can be adam, sgd(stochastic gradient descent), adam_w
# because of binary output values, we use binary_crossentropy loss function
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Training the Model

In [22]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
35/35 - 2s - 51ms/step - accuracy: 0.5515 - loss: 0.6892
Epoch 2/50
35/35 - 0s - 4ms/step - accuracy: 0.5515 - loss: 0.6797
Epoch 3/50
35/35 - 0s - 4ms/step - accuracy: 0.5515 - loss: 0.6722
Epoch 4/50
35/35 - 0s - 5ms/step - accuracy: 0.5515 - loss: 0.6671
Epoch 5/50
35/35 - 0s - 5ms/step - accuracy: 0.5515 - loss: 0.6627
Epoch 6/50
35/35 - 0s - 4ms/step - accuracy: 0.5515 - loss: 0.6579
Epoch 7/50
35/35 - 0s - 5ms/step - accuracy: 0.5515 - loss: 0.6537
Epoch 8/50
35/35 - 0s - 5ms/step - accuracy: 0.5515 - loss: 0.6488
Epoch 9/50
35/35 - 0s - 5ms/step - accuracy: 0.5697 - loss: 0.6435
Epoch 10/50
35/35 - 0s - 5ms/step - accuracy: 0.6007 - loss: 0.6383
Epoch 11/50
35/35 - 0s - 5ms/step - accuracy: 0.6117 - loss: 0.6327
Epoch 12/50
35/35 - 0s - 5ms/step - accuracy: 0.6144 - loss: 0.6268
Epoch 13/50
35/35 - 0s - 5ms/step - accuracy: 0.6217 - loss: 0.6205
Epoch 14/50
35/35 - 0s - 4ms/step - accuracy: 0.6427 - loss: 0.6142
Epoch 15/50
35/35 - 0s - 5ms/step - accuracy: 0.6427 - l

In [23]:
scaled_X_test

array([[0.38009937, 0.11250267, 0.66790876, 0.66254348],
       [0.87793234, 0.51420791, 0.24176708, 0.86962129],
       [0.36253236, 0.6533469 , 0.14420919, 0.38041779],
       ...,
       [0.3516936 , 0.62841491, 0.12375988, 0.52382069],
       [0.54302476, 0.64885668, 0.03868008, 0.3882538 ],
       [0.19293425, 0.74247045, 0.25236091, 0.22653105]])

In [24]:
y_test

array([1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1.,
       0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1.

# Prediction on Unseen Values

In [25]:
predictions = model.predict(scaled_X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 


In [26]:
# It gives the probability of being 1 (out of 0 and 1)
predictions

array([[0.6588417 ],
       [0.07415015],
       [0.6165702 ],
       [0.23144084],
       [0.06508421],
       [0.14362997],
       [0.28160816],
       [0.12491398],
       [0.72532964],
       [0.72532964],
       [0.22818264],
       [0.03313619],
       [0.61772287],
       [0.04019263],
       [0.04878009],
       [0.08960139],
       [0.72532964],
       [0.51503026],
       [0.10987019],
       [0.08394824],
       [0.72532964],
       [0.15515248],
       [0.04430258],
       [0.65036404],
       [0.5061671 ],
       [0.54221666],
       [0.0640254 ],
       [0.69421226],
       [0.1456248 ],
       [0.2526076 ],
       [0.72532964],
       [0.34639314],
       [0.6800773 ],
       [0.72532964],
       [0.72532964],
       [0.23020925],
       [0.11266615],
       [0.72532964],
       [0.41238368],
       [0.70751524],
       [0.39820558],
       [0.72532964],
       [0.1115562 ],
       [0.30316174],
       [0.6953716 ],
       [0.72532964],
       [0.05687945],
       [0.073

In [27]:
predicted_class = np.where(predictions > 0.5, 1, 0)
predicted_class

array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
    

# Evaluating the Model Performance

In [28]:
model.metrics_names

['loss', 'compile_metrics']

In [29]:
model.evaluate(x=scaled_X_test, y = y_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9401 - loss: 0.3040  


[0.3219158351421356, 0.9200000166893005]

In [30]:
from sklearn.metrics import confusion_matrix, classification_report

In [31]:
print(classification_report(y_test, predicted_class))

              precision    recall  f1-score   support

         0.0       0.90      0.97      0.93       157
         1.0       0.95      0.86      0.90       118

    accuracy                           0.92       275
   macro avg       0.93      0.91      0.92       275
weighted avg       0.92      0.92      0.92       275



In [32]:
model.save('models/model1.h5')

Hyperparameters are what we can change to get better values of w tensor and b.

In [33]:
from keras.models import load_model

In [34]:
load_model('models/model1.h5')

<Sequential name=sequential, built=True>